export const STAGES = ['START', 'PREVIEW_QUIZ', 'PREVIEW_QUESTION', 'QUESTION_AND_ANSWER', 'RESULT', 'SCORE_RESULT', 'FINISH'];

export const STAGE = {
    START: 'START',
    PREVIEW_QUIZ: 'PREVIEW_QUIZ',
    PREVIEW_QUESTION: 'PREVIEW_QUESTION',
    QUESTION_AND_ANSWER: 'QUESTION_AND_ANSWER',
    RESULT: 'RESULT',
    SCORE_RESULT: 'SCORE_RESULT',
    FINISH: 'FINISH'
}

export const MAPPED_STAGE = {
    START: 0,
    PREVIEW_QUIZ: 1,
    PREVIEW_QUESTION: 2,
    QUESTION_AND_ANSWER: 3,
    RESULT: 4,
    SCORE_RESULT: 5,
    FINISH: 6
}
