export {StarCustomIcon} from "./Star";
export {HexagonCustomIcon} from "./Hexagon";
export {SquareCustomIcon} from "./Square";
export {DotCustomIcon} from "./Dot";
export {SuperAdminCustomIcon} from "./SuperAdmin";
export {RatingCustomIcon} from "./Rating";
export {FullScreenCustomIcon} from "./FullScreen";
export {FullScreenExitCustomIcon} from "./FullScreenExit";
export {PeopleCustomIcon} from "./PeopleCustomIcon";
